name: Build cunumeric on GH

concurrency:
  group: ci-gpu-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches-ignore:
      - gh-pages  # deployment target branch (this workflow should not exist on that branch anyway)
  pull_request:
    branches-ignore:
      - gh-pages  # deployment target branch (this workflow should not exist on that branch anyway)

jobs:
  build:
    permissions: read-all
    runs-on: ubuntu-latest
    container:
      options: -u root
      image: rapidsai/devcontainers:23.06-cpp-cuda11.8-mambaforge-ubuntu22.04
      env:
        PYTHONDONTWRITEBYTECODE: 1
        SCCACHE_REGION: us-east-2
        SCCACHE_BUCKET: rapids-sccache-devs
        SCCACHE_S3_KEY_PREFIX: legate-cunumeric-dev
        VAULT_HOST: https://vault.ops.k8s.rapids.ai
        GH_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}"
        GITHUB_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN}}"
      volumes:
        - $GITHUB_WORKSPACE/out:/tmp/out
    steps:
      - name: Checkout legate-separate-build-scripts
        uses: actions/checkout@v3
        with:
          repository: 'sandeepd-nv/legate-separate-build-scripts'
          ref: sans_gh_cli
          path: lsbs

      - name: Checkout legate.core
        uses: actions/checkout@v3
        with:
          repository: nv-legate/legate.core
          ref: refs/tags/v23.03.00
          path: legate

      - name: Checkout cunumeric (= this repo)
        uses: actions/checkout@v3
        with:
          path: cunumeric
        
      - name: Build
        shell: bash -eo pipefail {0}
        run: |
          apt update;
          DEBIAN_FRONTEND=noninteractive \
          apt install -y --no-install-recommends \
              numactl rlwrap;
          mv lsbs/home/coder/.gitconfig /home/coder/.gitconfig;
          mv lsbs/home/coder/.local /home/coder/.local;
          mv legate /home/coder/legate
          mv cunumeric /home/coder/cunumeric

          chmod a+x /home/coder/.local/bin/*;
          chown -R coder:coder /home/coder/;

          su - coder -Pc "                                   \
          JOBS=1                                             \
          CMAKE_BUILD_PARALLEL_LEVEL=1                       \
          PATH=${PATH}                                       \
          VAULT_HOST=${VAULT_HOST}                           \
          GH_TOKEN=${GH_TOKEN}                               \
          GITHUB_TOKEN=${GITHUB_TOKEN}                       \
          SCCACHE_BUCKET=${SCCACHE_BUCKET}                   \
          SCCACHE_REGION=${SCCACHE_REGION}                   \
          SCCACHE_S3_KEY_PREFIX=${SCCACHE_S3_KEY_PREFIX}     \
          PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE} \
          RUSTC_WRAPPER=${RUSTC_WRAPPER} \
          CMAKE_C_COMPILER_LAUNCHER=${CMAKE_C_COMPILER_LAUNCHER} \
          CMAKE_CXX_COMPILER_LAUNCHER=${CMAKE_CXX_COMPILER_LAUNCHER} \
          CMAKE_CUDA_COMPILER_LAUNCHER=${CMAKE_CUDA_COMPILER_LAUNCHER} \
            ~/.local/bin/entrypoint bash -i build-all";

      - name: Upload build output
        uses: actions/upload-artifact@v3
        with:
          name: cunumeric-build-output
          path: ./out/*
